### ISSUE TITLE
Task Handler and workflow.results erroring out in 1.0.69

### ISSUE THREAD

**Issue by coderabhigupta** [conductor-sdk/conductor-python#169]
1.) Our workflow worker class/pattern gets an error trying to startup on using TaskHandler from conductor-python as a context manager:  with TaskHandler(self.workers, configuration) as task_handler: with AttributeError 'Name' object has no attribute 'value'   (this works on our current version 1.0.37

2.) We still see 'NoneType' object is not iterable when trying to iterate on the workflow.results : for wf in workflows.results
